name: Test coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Running tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero --statistics --exclude shad_env
      - name: Typing with mypy
        run: |
          python -m mypy compgraph/ examples/
      - name: Test coverage + tests
        run: |
           python -m pytest --cov-report=term-missing --cov=compgraph --cov-fail-under=95
