name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Running tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Typing with mypy
        run: |
          pip install mypy
          python -m mypy
      - name: Test coverage + tests
        run: |
           pip install pytest
           pip install pytest-cov
           python -m pytest --cov-report=term-missing --cov=compgraph --cov-fail-under=95
