name: Test coverage

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Running tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude shad_env
      - name: Typing with mypy
        run: |
          pip install mypy
          python -m mypy
      - name: Test coverage + tests
        run: |
           pip install pytest
           pip install pytest-cov
           python -m pytest --cov-report=term-missing --cov=compgraph --cov-fail-under=95
